x-payments-api: &payments-api-template
  build:
    dockerfile: ./Dockerfile
  deploy:
    resources:
      limits:
        cpus: "0.5"
        memory: "125MB"
  networks:
    - backend
    - payment-processor
  environment:
    - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
    - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080

services:
  load-balancer:
    image: nginx:latest
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend

  c1.payments.api:
    <<: *payments-api-template

  c2.payments.api:
    <<: *payments-api-template

networks:
  backend:
    driver: bridge
  payment-processor:
    name: payment-processor
    driver: bridge

