services:
  bun-payments-worker-1:
    build:
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "15MB"
    networks:
      - backend
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
