services:
  load-balancer:
    image: nginx:latest
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "15MB"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend

  c1.payments.api:
    build:
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "15MB"
    networks:
      - backend
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
