worker_processes  1;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    upstream payments_api_get {
        server c3.payments.api:3000;
    }
    upstream payments_api_delete {
        server c3.payments.api:3000;
    }
    upstream payments_api_post {
        server c2.payments.api:3000;
        server c1.payments.api:3000;
    }

    server {
        listen 9999;

        location / {
            set $upstream_name "";
            if ($request_method = GET) {
                set $upstream_name payments_api_get;
            }
            if ($request_method = DELETE) {
                set $upstream_name payments_api_delete;
            }
            if ($request_method = POST) {
                set $upstream_name payments_api_post;
            }
            proxy_pass http://$upstream_name;
        }
    }
}

